Fixes java.lang.NullPointerException on construction
java.lang.NullPointerException: Cannot invoke "cn.nukkit.plugin.PluginDescription.getPrefix()" because the return value of "cn.nukkit.plugin.PluginBase.getDescription()" is null